[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "zbotactions"
version = "0.1.0"
description = "ZBot action recording and playback tools"
dependencies = [
    "skillit",
]
